### ISSUE TITLE
cache_seed

### ISSUE THREAD

**Issue by nickknyc** [ruvnet/q-star#2]
Caveat, I am running in a venv and using pyautogen. 

```User: query what is gorp
[■□□□□□□□□□]User_proxy (to chat_manager):

query what is gorp

--------------------------------------------------------------------------------
Error: Unrecognized request argument supplied: cache_seed
User:
```

**Comment by mrmarten** [comment]
Had the same problem then i just changed on line 101 in q.py

`llm_config = {"config_list": config_list_gpt4, "cache_seed": 42}`

to 

`llm_config = {"config_list": config_list_gpt4}`

It then worked!

**Comment by nickknyc** [comment]
will give it a whirl in a bit - thanks!

**Comment by nickknyc** [comment]
Confirmed that worked - thanks @mrmarten

**Comment by nickknyc** [comment]
closed
